<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SpamsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('spam')->insert([
            ['word' => 'alinda.xyz'],
            ['word' => '.xyz'],
            ['word' => '<a'],
            ['word' => 'href'],
            ['word' => '100% more'],
            ['word' => '100% free'],
            ['word' => '100% satisfied'],
            ['word' => 'additional income'],
            ['word' => 'be your own boss'],
            ['word' => 'best price'],
            ['word' => 'big bucks'],
            ['word' => 'billion'],
            ['word' => 'cash bonus'],
            ['word' => 'cents on the dollar'],
            ['word' => 'consolidate debt'],
            ['word' => 'double your cash'],
            ['word' => 'double your income'],
            ['word' => 'earn extra cash'],
            ['word' => 'earn money'],
            ['word' => 'eliminate bad credit'],
            ['word' => 'extra cash'],
            ['word' => 'extra income'],
            ['word' => 'expect to earn'],
            ['word' => 'fast cash'],
            ['word' => 'financial freedom'],
            ['word' => 'free access'],
            ['word' => 'free consultation'],
            ['word' => 'free gift'],
            ['word' => 'free hosting'],
            ['word' => 'free info'],
            ['word' => 'free investment'],
            ['word' => 'free membership'],
            ['word' => 'free money'],
            ['word' => 'free preview'],
            ['word' => 'free quote'],
            ['word' => 'free trial'],
            ['word' => 'full refund'],
            ['word' => 'get out of debt'],
            ['word' => 'get paid'],
            ['word' => 'giveaway'],
            ['word' => 'guaranteed'],
            ['word' => 'increase sales'],
            ['word' => 'increase traffic'],
            ['word' => 'incredible deal'],
            ['word' => 'lower rates'],
            ['word' => 'lowest price'],
            ['word' => 'make money'],
            ['word' => 'million dollars'],
            ['word' => 'miracle'],
            ['word' => 'money back'],
            ['word' => 'once in a lifetime'],
            ['word' => 'one time'],
            ['word' => 'pennies a day'],
            ['word' => 'potential earnings'],
            ['word' => 'prize'],
            ['word' => 'promise'],
            ['word' => 'pure profit'],
            ['word' => 'risk-free'],
            ['word' => 'satisfaction guaranteed'],
            ['word' => 'save big money'],
            ['word' => 'save up to'],
            ['word' => 'special promotion'],
            ['word' => 'act now'],
            ['word' => 'apply now'],
            ['word' => 'become a member'],
            ['word' => 'call now'],
            ['word' => 'click below'],
            ['word' => 'click here'],
            ['word' => 'get it now'],
            ['word' => 'do it today'],
            ['word' => 'don’t delete'],
            ['word' => 'exclusive deal'],
            ['word' => 'get started now'],
            ['word' => 'important information regarding'],
            ['word' => 'information you requested'],
            ['word' => 'instant'],
            ['word' => 'limited time'],
            ['word' => 'new customers only'],
            ['word' => 'order now'],
            ['word' => 'please read'],
            ['word' => 'see for yourself'],
            ['word' => 'sign up free'],
            ['word' => 'take action'],
            ['word' => 'this won’t last'],
            ['word' => 'urgent'],
            ['word' => 'what are you waiting for?'],
            ['word' => 'while supplies last'],
            ['word' => 'will not believe your eyes'],
            ['word' => 'winner'],
            ['word' => 'winning'],
            ['word' => 'you are a winner'],
            ['word' => 'you have been selected'],
            ['word' => 'bulk email'],
            ['word' => 'buy direct'],
            ['word' => 'cancel at any time'],
            ['word' => 'check or money order'],
            ['word' => 'congratulations'],
            ['word' => 'confidentiality'],
            ['word' => 'cures'],
            ['word' => 'dear friend'],
            ['word' => 'direct email'],
            ['word' => 'direct marketing'],
            ['word' => 'hidden charges'],
            ['word' => 'human growth hormone'],
            ['word' => 'internet marketing'],
            ['word' => 'lose weight'],
            ['word' => 'mass email'],
            ['word' => 'meet singles'],
            ['word' => 'multi-level marketing'],
            ['word' => 'no catch'],
            ['word' => 'no cost'],
            ['word' => 'no credit check'],
            ['word' => 'no fees'],
            ['word' => 'no gimmick'],
            ['word' => 'no hidden costs'],
            ['word' => 'no hidden fees'],
            ['word' => 'no interest'],
            ['word' => 'no investment'],
            ['word' => 'no obligation'],
            ['word' => 'no purchase necessary'],
            ['word' => 'no questions asked'],
            ['word' => 'no strings attached'],
            ['word' => 'not junk'],
            ['word' => 'notspam'],
            ['word' => 'obligation'],
            ['word' => 'passwords'],
            ['word' => 'requires initial investment'],
            ['word' => 'social security number'],
            ['word' => 'this isn’t a scam'],
            ['word' => 'this isn’t junk'],
            ['word' => 'this isn’t spam'],
            ['word' => 'undisclosed'],
            ['word' => 'unsecured credit'],
            ['word' => 'unsecured debt'],
            ['word' => 'unsolicited'],
            ['word' => 'valium'],
            ['word' => 'viagra'],
            ['word' => 'vicodin'],
            ['word' => 'we hate spam'],
            ['word' => 'weight loss'],
            ['word' => 'xanax'],
            ['word' => 'accept credit cards'],
            ['word' => 'ad'],
            ['word' => 'all new'],
            ['word' => 'as seen on'],
            ['word' => 'bargain'],
            ['word' => 'beneficiary'],
            ['word' => 'billing'],
            ['word' => 'bonus'],
            ['word' => 'cards accepted'],
            ['word' => 'cash'],
            ['word' => 'certified'],
            ['word' => 'cheap'],
            ['word' => 'claims'],
            ['word' => 'clearance'],
            ['word' => 'compare rates'],
            ['word' => 'credit card offers'],
            ['word' => 'deal'],
            ['word' => 'debt'],
            ['word' => 'discount'],
            ['word' => 'fantastic'],
            ['word' => 'in accordance with laws'],
            ['word' => 'income'],
            ['word' => 'investment'],
            ['word' => 'join millions'],
            ['word' => 'lifetime'],
            ['word' => 'loans'],
            ['word' => 'luxury'],
            ['word' => 'marketing solution'],
            ['word' => 'message contains'],
            ['word' => 'mortgage rates'],
            ['word' => 'name brand'],
            ['word' => 'offer'],
            ['word' => 'online marketing'],
            ['word' => 'opt in'],
            ['word' => 'pre-approved'],
            ['word' => 'quote'],
            ['word' => 'rates'],
            ['word' => 'refinance'],
            ['word' => 'removal'],
            ['word' => 'reserves the right'],
            ['word' => 'score'],
            ['word' => 'search engine'],
            ['word' => 'sent in compliance'],
            ['word' => 'subject to…'],
            ['word' => 'terms and conditions'],
            ['word' => 'trial'],
            ['word' => 'unlimited'],
            ['word' => 'warranty'],
            ['word' => 'web traffic'],
            ['word' => 'work from home'],
        ]);
    }
}
